- LICENSE
- README.md
- osi_common.proto
- osi_datarecording.proto
- osi_detectedlandmark.proto
- osi_detectedlane.proto
- osi_detectedobject.proto
- osi_detectedoccupant.proto
- osi_environment.proto
- osi_groundtruth.proto
- osi_landmark.proto
- osi_lane.proto
- osi_lowleveldata.proto
- osi_modelinternal.proto
- osi_object.proto
- osi_occupant.proto
- osi_sensordata.proto
- osi_sensorspecific.proto
Please review the OSI initial commit.
Best regards
Carlo
> Initial commit of the Open Simulation Interface (OSI) Version 17

- osi_common.proto
- osi_sensordata.proto
the past  comment was misleading / not generally true.
> improved comment of SensorData::mounting_position

- .travis.yml
- doxygen_config.cmake.in
- test_cases.py
- Add a python script to perform simple test cases.
- Execute the python script in Travis CI.
> code analysis in Travis Ci (resolves #65)

- .gitignore
added python intermediate files' directory and extensions to git ignore list.
> Restructure gitignore

- osi_common.proto
For further details see issue #77
> change the order of width and length (resolves #77)

- osi_common.proto
- osi_lowleveldata.proto
For further details see issue #69
> Rename Polar3d to Spherical3d (resolves #69)

- osi_environment.proto
Definition of ambient illumination from various sources plus the SI units.
Categorization of various ambient illumination levels.
> AFTMMODELS-143 - define ambient illumination

- doxygen_config.cmake.in
More detailed collaboration diagrams for OSI html documentation (visualize basic datatypes and arrays).
> Collaboration Diagram

- doxygen_config.cmake.in
- osi_common.proto
- osi_detectedobject.proto
- osi_environment.proto
- osi_groundtruth.proto
- osi_lane.proto
- osi_object.proto
- osi_sensordata.proto
- osi_sensorspecific.proto
Reviewed OSI messages, extended documentation or clarification of documentation.
> Extend documentation (issue #97)

- osi_landmark.proto
Extension of enumerations.
This changeset is related to issue #97 (Reworking documentation).
> Landmarkextensions (related to issue #97)

- osi_landmark.proto
Complete some signs and add new signs and road markings.
Add possibility to define addition arrows on traffic signs (eg. on no parking signs). Introduce view_normal of displayed traffic sign symbol.
> Additional signs and road markings (issue #119)

- README.md
- osi_object.proto
Contains the BibTeX and motorbike naming fixes from PR #125 in cleaned up form.
> BibTeX and motorbike cleanups

- osi_featuredata.proto
- osi_groundtruth.proto
- osi_object.proto
- osi_occupant.proto
- osi_sensordata.proto
- osi_sensorspecific.proto
As per suggestion of  @CarloVanDriestenBMW this PR renames ego to host vehicle in all instances of the interface.
> Rename ego vehicle to host vehicle

- osi_lane.proto
This addresses issue #60 further, by including the surface texture or
fine roughness in addition to the surface_roughness field which is
indicating unevenness.
> Add road surface texture (or fine roughness)

- osi_detectedlane.proto
This PR add some documentation to address issue #137 @CarloVanDriestenBMW
> Add documentation (issue #137)

- osi_detectedlandmark.proto
Add new traffic sign shape geometries to the enumeration Geometry. #136
> Extension/detected traffic sign/geometry (issue #136)

- osi_detectedlane.proto
DetectedLaneBoundary message adapted to other Detected messages. (issue #137)
> DetectedXX messages  unified

- osi_common.proto
- osi_detectedlandmark.proto
- osi_detectedlane.proto
- osi_detectedobject.proto
- osi_detectedoccupant.proto
- osi_environment.proto
- osi_featuredata.proto
- osi_hostvehicledata.proto
- osi_landmark.proto
- osi_lane.proto
- osi_object.proto
- osi_occupant.proto
- osi_sensordata.proto
- osi_sensorinputconfiguration.proto
- osi_sensorview.proto
- osi_version.proto.in
Review documentation and compare to standardisation activities.
> Review documentation (issue #97)

- osi_environment.proto
- osi_groundtruth.proto
- osi_hostvehicledata.proto
- osi_landmark.proto
- osi_lane.proto
- osi_occupant.proto
This PR addresses issue #97 
Review and reformating of documentation.
Unifying enum names.
> Reformatting and review

- osi_environment.proto
Simple field addition of relative humidity, but lots of diffs to normalize whitespace at line ends for this file.
> Add relative humidity to environment data

- doxygen_config.cmake.in
- osi_common.proto
- osi_detectedlane.proto
- osi_detectedobject.proto
- osi_detectedoccupant.proto
- osi_detectedroadmarking.proto
- osi_detectedtrafficlight.proto
- osi_detectedtrafficsign.proto
- osi_featuredata.proto
- osi_lane.proto
- osi_object.proto
- osi_sensordata.proto
- osi_sensorview.proto
- osi_sensorviewconfiguration.proto
- osi_trafficsign.proto
remove link bugs and use homogenous notations.
> Remove doxygen link bugs (resolves #206 )

- README.md
- osi_lane.proto
- osi_roadmarking.proto
- osi_trafficlight.proto
- osi_trafficsign.proto
Doxygen links and text markings (necessary for travis CI).
> Small changes

- osi_trafficsign.proto
This PR address issue #220 
Mention all StVOs 450, 451 and 452 in documentation
> Extend documentation for traffic sign exit poles (resolves #220)

- osi_sensorview.proto
> Fix LidarSensorView signal_strength documentation

- osi_sensorview.proto
> Tighten documentation of ground truth filtering

- osi_environment.proto
Issue: #321 
Changes made:
* Created Date message based on UNIX time
* Added Date to EnvironmentConditions and adjusted Field Numbers
> Added Date to EnvironmentConditions (solves #321)

- .travis.yml
Fixing the duplicate bug, updating to bionic and adding treeview for easier browsing
See also issue: https://github.com/OpenSimulationInterface/open-simulation-interface/issues/339
[Here](https://travis-ci.org/vkresch/open-simulation-interface/builds) are some tests on my private repo performed which generated [this docu](https://vkresch.github.io/open-simulation-interface/index.html).
> Fix duplicate bug, update to bionic and add treeview

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
- .github/pull_request_template.md
Adding three types of issue templates
> Update issue templates

- doc/releases.rst
No related issue.
Update of the release naming conventions.
@jdsika pls review and merge the release links were in OSI after all :)
> Update release names

- doc/releases/v02.00.rst
- doc/releases/v02.01.rst
- doc/releases/v02.02.rst
- doc/releases/v03.00.rst
- doc/releases/v03.01.rst
- doc/releases/v03.02.rst
* Replace links to commit hash with link to release page
> Release documentation:

- README.md
> fix missing link to Windows installation

- doc/howtocontribute.rst
- doc/interfaceconventions.rst
- tests/test_invalid_enum.py
> Review: Onebitme patch 1

- .gitignore
- osi_common.proto
- osi_sensorviewconfiguration.proto
**Reference to related Issues:** 
- https://github.com/OpenSimulationInterface/open-simulation-interface/issues/389
- https://github.com/OpenSimulationInterface/open-simulation-interface/issues/432
**Description**
Message extension of _CameraSensorViewConfiguration_ to better support ray-tracer configuration inside the simulation environment.
This change will introduce a new set of messages for the ray tracer configuration when dealing with camera simulation.
It enables the configuration of the simulation environment by the sensor model in case of camera simulation and it improves mesasge consistency among Camera/Lidar/RadarSensorViewConfiguration. 
Is this a bug fix or a feature? Does it break any existing functionality or …
> Updated CameraSensorViewConfiguration Message

- README.md
This PR is an update to the README.md file for how to generate a simple scenario (through python). This will demonstrate new users of OSI quickly how to define and generate a scenario and how to visualize it.
-> this is a documentation update and cannot be tested
> Readme update for generating a scenario

- doc/misc/osi_reference.adoc
> feat(docs): Add link to reference documentation (#531)

- doc/misc/osi_vision.adoc
> Add vision topic

- doc/_config.adoc
Signed-off-by: Philip Windecker <philip.windecker@avenyr.de>
Hotfix 2 for config file.
> Added one more missing step

- doc/usecases/transforming_coordinate_systems.adoc
Relates to #687
Quick-Fix for missing title of Fig. 10 with coordinate system example
> Fixing title of Fig. 10 with coordinate systems

- .github/workflows/protobuf.yml
This completes the publication part for the actual release
> Add full release publication of python packages
