README.md, osi_common.proto
Added the changes discussed in the versioning issue #6
=> Updated README.md for versioning definitions

osi_common.proto, osi_datarecording.proto, osi_detectedlandmark.proto, osi_detectedlane.proto, osi_detectedobject.proto, osi_detectedoccupant.proto, osi_environment.proto, osi_groundtruth.proto, osi_landmark.proto, osi_lane.proto, osi_lowleveldata.proto, osi_modelinternal.proto, osi_object.proto, osi_occupant.proto, osi_sensordata.proto, osi_sensorspecific.proto
I did some minor clean up. Please have a look and let me know if you like it.
=> Minor cleanup

.gitignore, .travis.yml
This config file causes Travis CI to build this project with a matrix
build job. More information:
* https://docs.travis-ci.com/user/languages/cpp
* https://genbattle.bitbucket.io/blog/2016/01/17/c++-travis-ci/?
=> Add travis yaml

CMakeLists.txt
* Reusing the project name which avoids redeclaration and typos
* Using include directories instead of target include directories
for each target
* Removed FILE GLOB because it is evil and not recommended by Kitware
* Reformatted file
=> Simplified CMakeLists.txt

CMakeLists.txt
Due an oversight by me previous merge of #24 dropped the `target_link_library` dependencies.
=> Re-add missing target library dependencies.

osi_object.proto
Other enums are named differently
=> Fix naming according to the conventions

.travis.yml
Improves CI Cache usage by not redownloading/rebuilding dependencies when they are already in the cache. Also removes need for cache updates after build.
=> Speed up CI builds through better usage of caching

.travis.yml
Not using sudo is a good thing: it reduces boot time from 20-52s to 1-6s.
See: https://docs.travis-ci.com/user/ci-environment/
=> Remove need for sudo

osi_lane.proto
Clarified the meaning of left and right adjacent lanes. Also removed the legacy references to the Road message (does not longer exist). Fixes #33
=> clarify the lane descriptions

osi_object.proto
As discussed in my initial DaimlerSuggestions branch; the rotation matrix was missing in the comment.
=> Update rear axis frame calculation comment

osi_environment.proto
Hi all,
based on our discussions in issue #48 I created a branch.
Edit: the wiki definition of precipitation was ambiguous at one boundary 7.5 or 10mm per hour. I just went ahead and chose 10 mm. We can of course change that if someone wants it to be 7.5mm instead.
=> Insert pressure, temperature and precipitation

osi_lowleveldata.proto
We need the layer number for laserscanner point cloud data for easier processing and matching to real sensor data.
=> Add layer id to low level point cloud data.

CMakeLists.txt
Code using multiple copies of the static libraries in one process can
cause problems due to multiple copies of the protobuffer libraries not
interacting correctly. Change default target library to be a shared
library, add static variant as _static, and use object libraries to
optimize the building of the shared and _pic static libraries.
=> Add shared lib target, rename static lib (fix #55)

CMakeLists.txt
- Lower required version of cmake to 3.5, since that is easily
enough and supported by more distributions (e.g. Ubuntu 16.04 LTS).
- Add default build type selection logic, so that builds without
specified build type will default to either Release or Debug and not
to empty build type. Deals correctly with generators that support
multi-type builds, like VS.
=> Only require cmake 3.5, add default build type

osi_groundtruth.proto
To improve country specific traffic signs and other country specifics, I propose to add a country code regarding to ISO 3166/1 in GT. It was discussed at the OSI workshop 2017 in Ulm.
=> Add Country code to GT (Traffic Signs: What do we need? issue #62)

osi_detectedobject.proto, osi_sensordata.proto
Documentation how to store GT information in Sensordata is specified. Documentation of Vehicle rear axle is corrected in documentation.
Improve Documentation with suggestions from issue #104.
=> Extended Documentaton (also for issue #104)

osi_object.proto
This optional attribute allows sensor models that want to approximate
the influence of see-under without needing access to the whole vehicle
geometry.  Addresses the part of issue #99 that can be addressed
directly in ground truth data.
=> Add undercariage clearance to vehicles

CMakeLists.txt, osi_version.proto.in
This change allows the version number field in ground truth to work as expected, i.e. a version mismatch between sender and receiver can now be found. This change requires the sender to actively set the version number, for which the sender can use the current_interface_version file option of the osi_version.proto file to always use the version the sender was compiled against.
=> Fix version number field defaults (fixes #92)

osi_detectedobject.proto, osi_sensorspecific.proto
This relates to issue #97, replacing PR #112, to avoid gratuitous duplicate name changes. It splits out the non-renaming changes, letting naming issues be dealt with in a new, more global, PR.
=> Add ultrasonic-specific object data placeholder

osi_groundtruth.proto, osi_landmark.proto, osi_lane.proto
According to the OSI workshop in Ulm (November 2017), I propose this new lane model and the corresponding OSI messages. Change break downward compatibility.
=> New lane model (Handling Junctions with OSI::GroundTruth::Lane - issue #80)

osi_detectedlane.proto, osi_sensordata.proto
According to the OSI workshop in Ulm (November 2017), I propose this new detected lane model and the corresponding OSI messages. Change break downward compatibility.  Changes are similar to #110 (new Lane model).
issue #80, pull request #110
=> New detected lane model (related to Handling Junctions with OSI::GroundTruth::Lane - issue #80 and pull request #110)

osi_detectedlandmark.proto, osi_detectedlane.proto, osi_detectedobject.proto, osi_detectedoccupant.proto, osi_sensorspecific.proto
DetectedObject is adapted to standardised real sensor output structures. Other detected objects (like traffic sign/light etc.) are prepared.
DetectedObject list is adapted to the standardisation activities for real sensors. Other detected objects are draft.
=> Detected Objects adapted to real sensor structures.

osi_detectedobject.proto, osi_featuredata.proto, osi_groundtruth.proto, osi_modelinternal.proto, osi_sensordata.proto
This adds clarifying documentation to the timing-related fields, renames
the timestamp fields in DetectedObjectHeader and DetectionHeader to
indicate their measurment time related nature, adds a field named
last_measurement_time to the SensorData message to provide an upper
bound on embedded measurement times and removes legacy/ill-defined
fields.
=> Clarify and refactor timestamp field definitions

CMakeLists.txt, osi_sensorinputconfiguration.proto, setup.py
This is a first draft of the message used to configure the sensor input
between the model and the simulation environment. The mechanics of the
message interchange are determined by the model packaging.
It should be noted that the sensor input configuration mechanism is
separate from any mechanisms that are used to configure the sensor
model itself, which currently are packaging dependent.
Note that this pull request is to aid reviewing and further development,
more work to flesh out this approach if adopted is still needed. This is
just the result of discussions with @raueATconti based on the input by
@hschoen and others.
=> Add initial draft of sensor input configuration message (fix #98)

CMakeLists.txt, osi_modelinternal.proto, osi_sensordata.proto, osi_sensorinputconfiguration.proto, osi_sensorview.proto, setup.py
This cleans up SensorData, removes ModelInternal, SensorDataGroundTruth,
and introduces the new SensorView message which contains sensor-relative
and sensor-specific views on the GroundTruth. Note that this is a first
draft for discussion.
=> Refactor SensorDataGroundTruth, add SensorView

CMakeLists.txt, osi_hostvehicledata.proto, osi_sensordata.proto, setup.py
This changeset introduces HostVehicleData which comprises all vehicle
internal data that is available to the sensors (or in the future other
parts of OSI) as additional input. This includes e.g. GPS-sensor derived
data as well as e.g. engine ECU data, etc.  For now this only includes
GPS-sensor location data with error estimation.
=> Add host vehicle data as sensor input data

osi_landmark.proto
This PR adresses issue #138 
Define the orientation of the traffic sign's and road marking's bounding box. It defines how to apply the constraint (in which direction you have to apply the contrant).
Remove Typos TPYE_ --> TYPE_
=> Define BaseStationary orientation for OSI::Landmarks

osi_lane.proto
This PR adresses issue #60.
Because of missing definition of surface friction and the need for sensor simulation.
Surface friction is required for dynamic vehicle simulation.
=> Surface friction removed (issue #60)

osi_landmark.proto
@pmai Removed typos and change order of enum Type for traffic sign.
=> Improvements on extended traffic signs

osi_landmark.proto
This PR address issue #138 
Add enum UNIT to all optional values in landmarks (traffic sign, subl. sign, road marking).
Add additional values to subl. sign (to define day of the week range).
Remove exception for "pole_exit" enum entities. Now distance has set in value, e.g. exit in 100[m].
"Units" may be redundant because of GroundTruth.country_code?!
=> Feature/landmarks with values and units (issue #138)

osi_landmark.proto
(change Def of PR #150, address issue #138)
Change def. view normal from z-axis to x-axis.
Now view normal of a person and a traffic sign/roadmarking has the "same" definition.
=> Changed definition of traffic sign resp. roadmarking frame

osi_common.proto, osi_detectedobject.proto, osi_featuredata.proto, osi_landmark.proto, osi_object.proto, osi_sensordata.proto, osi_sensorinputconfiguration.proto, osi_sensorspecific.proto
This PR addresses issue #51 
Change OSI transformation between axis systems to ISO definition.
World frame -> vehicle frame -> sensor frame ...
Orientation is defined (world -> vehicle) rotate yaw -> rotate pitch -> rotate roll.
Note this is the international standard and differs from national american standard.
(OSI V2.xxx used national american standard)
**Additional Bugfixes:**
remove road marking orientation
remove camera sensor specific values. Redundant!
=> Use vehicle axis system definition of DIN ISO 8855

osi_detectedlandmark.proto, osi_detectedlane.proto, osi_detectedoccupant.proto
This PR addresses issue #74.
Add field age when missing.
Reorder fields ("similar order" for "all" fields).
renumber message field numbers afterwards.
=> Field age added to all detected entities ( issue #74)

osi_common.proto, osi_datarecording.proto, osi_detectedobject.proto, osi_featuredata.proto, osi_landmark.proto, osi_lane.proto, osi_object.proto, osi_sensordata.proto, osi_sensorspecific.proto, osi_sensorview.proto
This PR addresses issue #97.
Review doxygen links.
Review documentation layout in proto (80 chars).
Review doxgen commands.
Remove typos
**Rename DetectionHeader --> SensorDetectionHeader**
Review TrafficSignTyps and **add some traffic signs.**
Add references to traffic sign images.
**Generalize traffic signs** (30km/h zone --> speed limit zone & value & value_unit)
Rename **repeated field names (plural or list as suffix).**
Add units to message field documentation.
=> Review documentation (issue #97)

osi_detectedlandmark.proto, osi_detectedlane.proto, osi_detectedobject.proto, osi_detectedoccupant.proto, osi_featuredata.proto, osi_sensordata.proto
=> New proposal for SensorID List

osi_detectedlandmark.proto, osi_landmark.proto
This PR addresses issue #70 .
Review and reformating of documentation.
Unifying enum names.
Change Traffic Lights from semantic representation (light box) to syntactic representation (light bulbs)
=> Replacing semantic Traffic Lights with Traffic Light Bulbs (issue #70)

osi_detectedlandmark.proto, osi_groundtruth.proto, osi_landmark.proto, osi_sensordata.proto
This PR addresses issue #166.
Add landmarks and detected landmarks as new OSI messages.
Add landmarks to GT and detected landmarks to SensorData.
Move field measurement_state to Candidate... messages.
=> Landmarks added (issue #166)

osi_sensordata.proto
This is relevant for e.g. sensor fusion models that merge multiple
SensorData inputs into one SensorData output.
=> Allow repeated SensorView copies in SensorData

osi_object.proto
This PR addresses issue #177 and #178
=> Extend definition of vehicles

osi_sensorview.proto, osi_sensorviewconfiguration.proto
This PR adds generic sensor sub views (and sub configurations) to address physical sensors which either do not match the other technologies, or do not wish to use the services provided for those. This is a minimal PR, not splitting up ground-truth generation and making it view and sensor-coordinate specific.
This PR also addresses the use of doubles for times in SensorViewConfiguration, changing those to be Timestamps.
=> Generic Sensor Sub Views and Timestamps

osi_detectedlandmark.proto, osi_detectedlane.proto, osi_detectedobject.proto, osi_detectedoccupant.proto
All messages expect DetectedObject message
=> Restructuring DetectedXXX messages

README.md
http://www.graphviz.org/Download_windows.php currently leads to a 404 page; updated readme with new link.
=> Fix graphviz link

.gitignore, doxygen_config.cmake.in, osi_object.proto, osi_sensordata.proto, osi_sensorview.proto, osi_sensorviewconfiguration.proto
from doxygen documentation generation.
=> Remove warnings

osi_common.proto, osi_detectedobject.proto, osi_environment.proto, osi_featuredata.proto, osi_groundtruth.proto, osi_lane.proto, osi_object.proto, osi_sensordata.proto, osi_sensorview.proto, osi_sensorviewconfiguration.proto
Add doxygen links and remove wrong doxygen links.
Extend documentation for dashed lane boundaries (issue #205 only extended documentation).
Correct snr unit (issue #210).
=> Update Documentation (resolves #210)

README.md, osi_roadmarking.proto, osi_trafficsign.proto
Remove doxygen windows bug (roadmarking types are not correct).
Add StVO road markings as symbolic signs in documentation of traffic signs (resolves #229 and resolves #230 and additional road markings).
=> Extended documentation traffic sign/road markings (resolves #229) (resolves #230)

.travis.yml, README.md, convert-to-proto3.sh
This change allows usage of the OSI definitions on proto3 syntax,
while remaining on-the-wire-compatible with the official proto2
syntax.
Note that Travis CI build is also amended to build both proto2
and proto3 versions so that portability fails will be detected early.
=> Add proto3 support via script to map file syntax

osi_featuredata.proto, osi_sensorviewconfiguration.proto
Handle changes which were targeted for v3.0.1
=> Enhance documentation as per issue #250

setup.py
This change builds the protobuf files inside the osi3 package path
for Python2 to ensure that relative imports work, while not breaking
the general cmake build setup.  It also moves the protobuf generation
to the build command phase for tidiness.
=> Fix python3 relative import issue and setup.py

osi_groundtruth.proto
Using field number 16 because the projection string will not be a small field, so `14,15` can be used in future releases for `repeated` or smaller fields.
=> Add proj4 string to GroundTruth fixes #276

osi_object.proto
The discussion in issue #294 
This pull request enables to patch missing emergency vehicle and service vehicle. 
The concept is as follows: **the fact that a vehicle is either emergency vehicle or a service vehicle can be inferred from the state of the light.**
=> Added Emergency and Service vehicle illumination.

doxygen_config.cmake.in, osi_featuredata.proto
@CarloVanDriestenBMW: Proposal for camera detections.
=> Camera detecions

CMakeLists.txt
Commit ce92c01340262e70674be02a65fbdcc4e983a96b changed the
open_simulation_interface target from being a shared library to a static
library (for which we already have the open_simulation_interface_static
target). This reverses that part of the patch.
This seems to be an inadvertant change that slipped through the cracks, and needs to be fixed quickly, since it breaks all users of the shared library (i.e. everyone building on Linux/Unix systems, and even some using the DLL on Windows).
This is an urgent fix, since this more or less breaks 3.1.0 for most consumers, so should be included in a quick 3.1.1 followup release (making the current 3.1.1 planned release a 3.1.2).
=> Revert breakage in ce92c013 to CMake build of SO

osi_adas_function.proto, osi_common.proto, osi_driver_inputs.proto, osi_vehicle.proto
I did some consistency updates that are, in my opinion, better choices in term of readability and _confuseless_ style.
- renamed `Steeringwheel` to `Steering Wheel` and Activationstate to `Activation state` (the proper English names), in _snake_case_ and _CapWord_,
- wrapped the lines to 80 characters as in the other .proto files,
- renamed boolean attribute to `is_...` and `are_...` to improve readability and reduce confusion,
- renamed `handbrake` attribute to `handbrake_position` to specify what is it about,
- change hand_on_detection to hand_**off**_detection, which is the right official name for this kind of system — that also reverse the boolean state. There is a choice to make between OSI-message consistency (_all the attributes need to be true to start the vehicle_) and reality …
=> Extension adas vehicle driver inputs

osi_common.proto, osi_driver_inputs.proto, osi_vehicle.proto
I tried to clarify its state and to differentiate power train states and lever states.
Any comment would be welcomed.
=> Improvement on Gear handling (HMI-ADAS extension)

.travis.yml, tests/test_invalid_message.py
No related issue. Just for more test coverage in the CI pipeline which includes also the protobuf 3 syntax through the usage of the script [convert-to-proto3.sh](https://github.com/OpenSimulationInterface/open-simulation-interface/blob/master/convert-to-proto3.sh).
_What is this change?_
This PR divides the travis ci into two stages one for testing and one for depolying. Inside the stage testing there will be executed two jobs in parallel. One job is for testing the build with protobuf 2 syntax the other job is for testing the build with protobuf 3. The deploy stage has the same code as the protobuf 2 test because currently you can't share files between jobs or stages see quote below from [here](https://docs.travis-ci.com/user/build-stages/#data-persistence-between-stages-and-jobs):
> It …
=> Add proto3 syntax check

doc/description.rst
Resolves https://github.com/OpenSimulationInterface/open-simulation-interface/issues/100.
Correcting the bibtex citation in the [documentation](https://opensimulationinterface.github.io/osi-documentation/open-simulation-interface/doc/description.html#citing). The new change will be seen tomorrow when the next cron job will be executed.
@jdsika @PhRosenberger pls check and merge.
=> Fixing bibtex citation

doc/description.rst, doc/fileformat.rst, format/OSITrace.py, format/osi2read.py, format/txt2osi.py
There is an [issue](https://github.com/OpenSimulationInterface/osi-visualizer/issues/30) on how to define files which can be read by the visualizer.
This PR defines the OSI format for storing multiple messages in one file based on the length of the message. It also provides a script to convert from currently used separated trace files by `$$__$$` to to the OSI format. This is made so we avoid confusion on how to correctly define OSI file formats and to use [Google official suggestion](https://developers.google.com/protocol-buffers/docs/techniques?csw=1#streaming) on how storage of multiple messages should be handled. It is optional to convert into lzma compressed files since this compression algorithm does a good job on compressing ~1.3gb *.txt into 2,4mb *.txt.lzma (540x smaller, …
=> Added osi file format converter and read converter

.travis.yml, README.md, setup.py, tests/test_comment_type.py, tests/test_doxygen_output.py, tests/test_invalid_comment.py, tests/test_invalid_enum.py, tests/test_invalid_html.py, tests/test_invalid_message.py, tests/test_invalid_punctuation.py, tests/test_invalid_tabs.py, tests/test_newline.py, tests/test_non_ascii.py
None - These are out of context quality of life improvements in the automated test suite
_This PR contains #359 except from the branch pushed to the osi organization instead of to my fork. Maybe travis isn't configured to build fork PRs (I think this is the default due to potentially leaking env secrets into forks.)_
I saw some long-hanging fruit in improving these tests. I hope the commit messages do
well enough to explain the change/intention behind it. If not, feel free to comment on details :)
This PR switches the build to python3. Python2 is EOL in just a few days so I think it is reasonable to makes this switch (let me know if there are reasons not to do this!).
=> Hk improve tests

.travis.yml, doc/description.rst
After reviewing improvements to the repository I noticed some redundant code in the ci pipeline. I also added some documentation concerning the conversion of proto2 files to proto3 files (Resolves https://github.com/OpenSimulationInterface/open-simulation-interface/issues/257).
This PR removes redundant code from the CI pipeline which checked the proto3 syntax build. Since we now have split this build syntax check into two jobs which run in parallel these lines of code are not needed anymore.
@jdsika pls review and merge :)
=> Remove redundant build3 proto3 syntax check

osi_sensorviewconfiguration.proto, tests/test_units.py
The following [PR](https://github.com/OpenSimulationInterface/open-simulation-interface/pull/365) corrected the documentation of units according to the DIN norm in OSI. To complete the correction a test needs to be added which would have failed when the correction was not made.
This PR adds a test for checking:
- Units defintion must be on a separate line (I made a correction in the osi_sensorviewconfiguration.proto file.)
- The syntax must be: '// Unit: m'
- First letter of Unit must always be uppercase
- Units must not be enclosed with any brackets
@jdsika @PhRosenberger pls review and let me know your thoughts and improvements.
=> Added test for units

doc/fileformat.rst
Resolves https://github.com/OpenSimulationInterface/open-simulation-interface/issues/373
Adding documentation for a best practice naming convention for trace files. The real implementation of the validation part can be in future performed by the OSI-Validator. 
@jdsika review pls :) and add you custom info if needed
=> File naming

osi_featuredata.proto
- Removed incorrect rule due to misinterpretation of the word "absolute"
- Improved comment so that psoitive values are correctly interpreted
@pmai approve and merge
=> Resolves issue #306

doc/description.rst
This resolves #346, by reserving all field numbers above 10000 for extensions. Since the extension mechanism of proto2 is not available in proto3, this is currently only fixed in the documentation, and will be taken into the conventions documentation prior to release.
=> Reserve fields above 10000 for extensions (#346)

osi_trafficsign.proto
Documentation bug probably due to 2017 renumbering of signs
This is purely cosmetic, but should be fixed to avoid confusion (that said, I'm not sure whether it would not be better to remove all references to "other" signs, since this is error-prone and probably not that helpful anyway).
=> Fix reference for left version of StVO 214

osi_trafficsign.proto
Documentation bug probably due to 2017 renumbering of signs
=> Fix image reference for StVO 222 and 222-10

doc/howtocontribute.rst
Signed-off-by: Ben Engel <benjamin.engel@asam.net>
See e.g. #344 
Add some initial documentation on DCO requirements and sign off for git commits. 
This is a first pass at extending the contribution guidelines to make sure they adhere to ASAM requirements for an open source project. We will need to keep iterating on these as we go along.
@jdsika @pmai
=> Add DCO information to Contribution Guidelines

format/OSITrace.py
For message iteration there is currently a bug in which the range cannot be specified (https://github.com/OpenSimulationInterface/open-simulation-interface/issues/426).
This PR replaces hte while loop iteration with the for loop iteration over the messages inspired from the osi-validator.
It fixes the index specification of OSI trace files. (Fixes #426)
I ran manual test with an osi trace file to get messages by index. I also tested the conversion from *.txt -> *.osi and made the *.osi file also readable.
@tpajenkamp-dspace let me know if this PR fixes your issue. Please test it with your trace file and let me know if it works.
=> Fix message iteration by index and range

osi_groundtruth.proto
This PR represents a PR from the SETLevel4To5 project, adding an optional model_reference to the top-level ground truth, to allow the specification of a 3D model representing the environment: This model covers the static parts of the environment that are not provided as individual models referenced from ground truth objects like moving or stationary objects. It is implementation-specific which exact parts this world model contains, e.g. whether it contains street geometries, or whether those are derived automatically from a map reference, if one is provided.
Signed-off-by: Pierre R. Mai <pmai@pmsf.de>
=> Add global model reference to ground truth

osi_trafficlight.proto, osi_trafficsign.proto
No related issue.
Beside the model_references in stationary and moving object, it can be helpful to have a reference packed within traffic lights and traffic signs (main sign + supplementary sign).
The model_reference can be used e.g. to tell which 3D-model should be visualized.
- What is this change?
Added three model_references
- What does it fix? Is this a bug fix or a feature? Does it break any existing functionality or force me to update to a new version?
It's a new feature the helps to use osi for visualization. 
It works, testing was company internally.
@pmai , @engelben 
This would be a PR for the planned CCB.
=> Extension of traffic lights and signs regarding model references

CMakeLists.txt, doc/osifiles.rst, osi_common.proto, osi_trafficcommand.proto, osi_trafficupdate.proto, setup.py
The basis of this PR is the consolidated traffic participant feature branch from the SETLevel4To5 project, which provides for traffic participant modeling through the newly introduced TrafficUpdate and TrafficCommand top-level messages. Note that this initial contribution has already been enhanced inside the ASAM project as well.
This draft PR is created in order to highlight this proposal and allow coordinated further work on it inside the relevant ASAM WPs.
=> Introduction of Traffic Participants and releated Top-Level Messages

osi_lane.proto
This is an interim solution used in the SETLevel4To5 project for lane type information from OpenDRIVE coordinated with ASAM to allow for e.g. pedestrian model implementation.
Signed-off-by: Pierre R. Mai <pmai@pmsf.de>
=> Add lane sub-types to represent OpenDRIVE lane type information

CMakeLists.txt
No open issue for this pull-request.
Tell cmake which compiler to use on apple machines: Building the project out of the box on apple machines will cause Cmake to fail. Setting the correct default compiler will fix this issue. Extending CMakeLists.txt fixes the build-process and enables an 'out of the box' build without errors.
@pmai
Crossed entries were considered as not required.
- ✅ My code and comments follow the [style guidelines](https://opensimulationinterface.github.io/osi-documentation/osi/commenting.html) and [contributors guidelines](https://opensimulationinterface.github.io/osi-documentation/osi/howtocontribute.html) of this project.
- ✅ I have performed a self-review of my own code.
- ❌ I have made corresponding changes to the …
=> set default c11 compiler for apple machines

CMakeLists.txt, doc/osifiles.rst, osi_logicaldetectiondata.proto, osi_sensordata.proto, setup.py
LogicalDetectionData provides feature data in the virtual cartesian
sensor coordinate system and is therefore suitable for fusion at the
feature data level, whereas FeatureData is not.
Signed-off-by: Pierre R. Mai <pmai@pmsf.de>
This PR coming from the SETLevel4To5 project is partly related to #367, and tackles the issue that the current `FeatureData` interface is strictly limited to one physical detector/sensor, since the coordinate system is spherical. This makes it more or less impossible to transport fusioned data, which must necessarily reside in one common coordinate system. The naming also tries to align with DIS 23150 (further alignment might also recommend renaming of `FeatureData`, which is however not included in this PR so as to remain backward compatible for now).
=> Add new LogicalDetectionData message to SensorData

tests/test_rules.py
Earlier versions of this check erroneously treated the end of an enum
as the end of its enclosing message, leading to problems with nested
enums if they appeared not at the end of its enclosing messages.
Signed-off-by: Pierre R. Mai <pmai@pmsf.de>
=> Make handling of enums in rules check more robust

osi_object.proto
The value is needed for visualization needs. To see how the steering wheel moves from other cars, but also your own (especially VR, when you sit in the car.
It can not be derived from the wheel angle in an accurate way.
What is this change? What does it fix?
The value is needed for visualization needs. To see how the steering wheel moves from other cars, but also your own (especially VR, when you sit in the car.
It can not be derived from the wheel angle in an accurate way.
New feature.
In another branch the signal was implemented and tested.
=> Add steering wheel angle

.github/pull_request_template.md
None.
Checklist reworked as decided in the Q4/2020-Meeting at ASAM (27.01.2021).
The checklist inside each PR to tell how "grown up" your PR is.
I also deleted the "Mention a member"-part as this is done by assigning reviewers (agree on that?)
PR-Improvement.
PR-Improvement.
The test is done by this PR.
See the new content from here below:
If all boxes are checked or commented and you achieved at least one positive review, you can assign the label readyForCCB.
=> Reworked Checklist for each PR

osi_trafficcommand.proto
Signed-off-by: Nader Thomas <thomas.nader@bmw.de>
As discussed in the CCB-Meeting.
Restructuring of the different traffic action definitions as discussed in the CCB-Meeting.
==> To make the code more structured and give a better overview (especially by implementing).
Moved the different traffic action definitions in message TrafficAction as discussed in the CCB-Meeting.
Add @mentions of the person or team responsible for reviewing proposed changes.
=> Moved different action definitions into message trafficAction.

osi_detectedobject.proto, osi_object.proto
Add a reference to a related issue in the repository.
Add the assigned lane id to the vehicle classification as it is the case with other entities (e.g. traffic signs)
Add the assigned lane id to the vehicle classification as it is the case with other entities (e.g. traffic signs)
It is a bug fix. Fields got altered, therefore minor version upgrade.
Documentation was build
Vehicle Classification without assigned lane id
Vehicle Classification with assigned lane id
@jdsika @ThomasNaderBMW
=> Move assigned_lane_id in osi_object.proto to VehicleClassification

doc/releases.rst, doc/releases/v03.03.rst
This PR adds the release documentation to OSI so that it can be viewed in the [OSI release documentation](https://opensimulationinterface.github.io/osi-documentation/open-simulation-interface/doc/releases.html).
-> Changes to documentation does not need tests.
=> Added release notes for 3.3.0

osi_groundtruth.proto
PS: maybe the expression "opaque reference" could be elaborated.
Add a reference to a related issue in the repository.
Add a description of the changes proposed in the pull request.
=> Correct typos in model_reference comments in osi_groundtruth.proto

osi_lane.proto, osi_roadmarking.proto
As suggested in #504:
**1. Color orange is added to road mark colors**
**2. Color violet is marked as deprecated**
What is this change? --> only extension
What does it fix? --> harmonisation with OpenDrive
How has it been tested? --> only extension
=> Harmonization of road mark colors with OpenDRIVE

osi_common.proto, osi_environment.proto, osi_lane.proto, osi_object.proto, osi_occupant.proto, osi_roadmarking.proto, osi_trafficlight.proto, osi_trafficsign.proto
OSI currently offers no options for an internal data management of the source of an object. Therefore an additional identifier is proposed to reference to external standards or external sources like models or physical sensors. For an exchange and a traceability, especially in the post processing of tests, it is important to identify the source of an object.
Currently, there is only a numeric identifier to describe the different object within OSI. As there should be an interoperability within other standards, especially the OpenX-Standards, but also third party simulations, an additional and more generic reference identifier is needed.
As the identification in different standards are more complex than only using a numeric id, a representation based on a list of strings is chosen. The …
=> Definiton of external references

osi_object.proto
Add a reference to a related issue in the repository.
Add a description of the changes proposed in the pull request.
=> Feature/tp/add speed bumps #448

doc/architecture/feature_data.adoc, doc/architecture/ground_truth.adoc, doc/architecture/sensor_data.adoc, doc/architecture/sensor_view.adoc, doc/architecture/sensor_view_configuration.adoc, doc/architecture/traffic_command.adoc, doc/architecture/traffic_update.adoc, doc/open-simulation-interface_user_guide.adoc
This PR resolves #506. 
The new content is supposed to explain the general ideas behind the different top-level messages.
* Is the information sufficient for understanding the basic idea behind these top-level messages?
* Is important information missing?
* Is the information correct?
=> Describe top-level messages (#506)

doc/architecture/formatting_scripts.adoc, doc/architecture/trace_file_formats.adoc, doc/architecture/trace_file_naming.adoc
This PR resolves #520 
Fills topics with content:
- OSI trace file formats
- OSI trace file naming conventions
- Trace-file formatting scripts.
=> Describe trace file formats and naming

osi_trafficupdate.proto
Signed-off-by: Habedank Clemens <qxs2704@europe.bmw.corp>
Add a reference to a related issue in the repository.
Add a description of the changes proposed in the pull request.
Clarifying semantics after feedback from SETLevel project. The semantics for other potential use cases, e.g. multiple TrafficParticipants packaged in one model would need to be elaborated and specified (OSMP + OSI) and are therefore currently not supported. A trailer seems unproblematic in this regard, so keeping the field repeated is possible. 
If you can’t check …
=> clarified semantics currently supported with TrafficUpdate

osi_common.proto, osi_detectedlane.proto, osi_detectedobject.proto, osi_detectedroadmarking.proto, osi_detectedtrafficlight.proto, osi_featuredata.proto, osi_lane.proto, osi_object.proto, osi_roadmarking.proto, osi_trafficlight.proto
Signed-off-by: Thomas Sedlmayer <tsedlmayer@pmsfit.de>
This PR emerged from the Harmonisation group and the discussions related to https://github.com/OpenSimulationInterface/open-simulation-interface/issues/512. It should serve as a basis for further discussion. The color models (Grey, RGB, RGBIR, HSV, LUV) were adopted from the ISO-23150. 
It is not completely clear yet where and how to apply the new message and how to manage the transition to complement or replace existing color enums. As a result from discussions, color enums that represent **semantic meaning** (e.g. traffic light colors, lane marking colors, lane boundary colors) should probably be kept as is or could be unified as separate enums (e.g. "SemanticColors"). Semantic colors are colors that specifically specify an objects …
=> Introducing new color models

.gitignore
Signed-off-by: Yan QiDong <yanqd0@outlook.com>
2 lines are added to `.gitignore`.
- `osi3/`, this is missing after `pip install .` or `python setup.py develop` is executed. The python package name has changed from `osi` to `osi3` for a long time.
- `pyproject.toml`, this file will be generated when this project is used with `pipenv`.
This is a general, simple change. It is helpful for me, maybe also for others.
---
I don't know which reviewer should be assigned to. An ownership table may be helpful in the guidelines, which is missing and recommended.
=> Add osi3 and pyproject.toml to .gitignore

osi_lane.proto
Signed-off-by: Thomas Sedlmayer <tsedlmayer@pmsfit.de>
Description:
Currently, there are some issues concerning the definition of dashed lines in OSI (e.g. https://github.com/OpenSimulationInterface/open-simulation-interface/issues/539, https://github.com/OpenSimulationInterface/open-simulation-interface/issues/205). Also, @HendrikAmelunxen named an issue with trimmed SensorView information, where some preceding boundary points could be missing and it would not be clear which boundary point has been the first one in order to restore where dashes or gaps are on the boundary line.
In the harmonisation working group it was proposed to add an enum to boundary points (for dashed lines only) that indicates start/end/continuation of a dash. This could independently describe dash locations even …
=> Add dash property to boundary points

osi_featuredata.proto
echo_pulse_width added in osi_featuredata.proto for message LidarDetection. 
As intensity is in % and echo_pulse_width is in m, such a field is currently missing in OSI for LidarDetectionData.
It is necessary to transfer echo_pulse_width since sensors like Ibeo LUX or Valeo SCALA are having this as an output instead of intensity.
The PR comes out of the SET Level project, where it has already been approved by the project-internal OSI-CCB.
=> echo_pulse_width added in osi_featuredata.proto for message LidarDetection

osi_common.proto, osi_hostvehicledata.proto, osi_trafficupdate.proto
#545 
See the linked issue for more details, but at a high level, this adds the ability for a host vehicle to report details about the internal state of automated driving functions.
It also adds `HostVehicleData` to a `TrafficUpdate` to allow this information to be reported from a SuT to the simulator, or other simulation entities.
(`HostVehicleData` is already a top level message, and embedded in other "reporting" type messages, to allow this information to be propagated further if necessary)
=> Add automated driving function state to host vehicle data

README.md
@pmai there is a security issue with protobuffer that created an automatic version bumb PR in [osi-validation](https://github.com/OpenSimulationInterface/osi-validation/pull/41). I am wondering three things here:
1) Why not bumb to the newest version [3.19.4](https://github.com/protocolbuffers/protobuf/releases)?
2) Where are the places we have defined the protobuffer version in this repository?
3) Do we need to create a new patch version for OSI?
=> Dependebility: Bumb protobuf version

doxygen_config.cmake.in
- Automatically generate brief output, so the attribute list is more
informative.
- Do not sort detailed description alphabetically. This means the detailed
description is in the same order as the attribute list and the source
file.
- Translate \rules and \endrules to something more readable. As a nice
side effect, this removes a lot of warnings when building the
documentation.
Signed-off-by: Thomas Bleher <thomas.tb.bleher@bmw.de>
=> Tweak Doxygen output

osi_environment.proto
With this PR we try to fulfill the needs of harmonization of the Issue #544, #577, #578 as well as Issue #255 and the PR #582 
The discussion has been over a year now and we try to merge with small steps.
So far we only added the `Sun`, `CloudState` as well as the `Wind` as messages.
This should help merging this PR in Version V3.5.0. more easily.
There is another PR #601 in order to get the Enum types and continues values for e.g. `Fog`, `Precipitation`, `Ambient Illumination` to V4.0.0. #577 #578 #255 
According to #544 the following data structures were created within this PR:
- Sun:
- azimuth [rad]
- elevation [rad]
- intensity [lx]
- Wind:
- direction [rad]
- speed [m/s]
- CloudStates (__enum__):
- Level 1 - 8 to tell how many clouds cover the blue sky
most of these requirements are …
=> Environmental conditions, added Sun, Wind, CloudState

osi_trafficcommand.proto, osi_trafficcommandupdate.proto
This PR comes from the SET Level project.
Offers a basic backchannel for traffic participant models regarding successful/unsuccessful execution of TrafficCommands. Interpretation is then up to the scenario engine. 
=> Traffic Command Update

osi_referenceline.proto
Fixes a copy-paste error in the documentation.
=> Correct documentation of Identifier of ReferenceLine

osi_hostvehicledata.proto
The operating state of the vehicle.
Signed-off-by: Thomas Nader <Thomas.Nader@bmw.de>
Beyond sheer driving use cases, this extension is needed to show if a vehicle is actually operating or not.
It is an overall state that may turn off or on the electrical consumers in the vehicle.
An improvement.
No bug fix.
It is a feature, no break.
With a similar signal on a HiL(dynamic+RBS) and a mockup.
=> Introducing Operating States

.gitignore, CMakeLists.txt, open_simulation_interface-config.cmake.in
Resolves #550 
This PR aims to modernize the installation logic of the project by:
* removing redundant warnings
* prefix cache variables with the project name
* provide namespaced alias targets usable from the build tree
* provide a namespace for the export set
This modernization will make the project usable via [FetchContent](https://cmake.org/cmake/help/latest/module/FetchContent.html) by a downstream project.
=> #550 cmake build is missing key features to be properly usable via fetchcontent

osi_object.proto
Extending the Wheel Data transmitted by friction coefficients.
Doing this, it is possible to run a dynamic/vehicle model by using SensorView or out of standard -so far- TrafficUpdate.
It is a feature and not compatibility breaking.
Yes and it is the only missing value so far.
=> Extending Wheel Data by Friction Coefficient

osi_object.proto
[Issue](https://github.com/OpenSimulationInterface/open-simulation-interface/issues/584)
Added Role to VehicleClassification in alignment with OSC 1.2
=> Add Role to VehicleClassification

osi_lane.proto
Added additional documentation on how the boundary between lanes at different heights should be modeled.
- Additional documentation.
- Missing documentation on how to model lane boundaries.
=> Concretize lane boundary modelling for lanes at different heights

doc/_config.adoc
Quick Fix for Asciidoctor build
=> Fix path to asciidoc-resources

.github/workflows/antora-generator.yml
Since no secrets will be available for security reasons, do not try to trigger antora builds when those secrets are not available.
=> Never trigger antora builds for PRs from forks

osi_trafficsign.proto
- Clarify definition of VARIABILITY_FIXED and VARIABILITY_VARIABLE to differentiate from new types
- Add new types VARIABILITY_VARIABLE_MOVABLE and VARIABILITY_VARIABLE_MUTABLE
As already mentioned by @jdsika in #623, the differentiation between mutable content (e.g. traffic sign type) and changes in position of traffic signs is not given yet.
To maintain backwards compatibility the existing type VARIABILITY_VARIABLE is essentially kept as it is. It still describes traffic signs that CAN BE semantically and positionally variable. This means that it has to be expected that the traffic sign's type and position could change over time (exactly as it is with the current OSI version). If further differentiation in terms of semantics and position is desired, the new types …
=> Add new traffic sign variability types

osi_object.proto
feat(vehicle classifications): add classification for stand-up scooters, motivated by possible NCAP target type
refers to issue #673
This adds a new enum Type in vehicle classification for stand-up or kickboard scooters.
- [/] My suggestion follows the [style and contributors guidelines](https://opensimulationinterface.github.io/osi-antora-generator/asamosi/latest/specification/contributing/start_contributing.html).
- [/] I have taken care about the [message documentation](https://opensimulationinterface.github.io/osi-antora-generator/asamosi/latest/specification/contributing/commenting_messages.html) and the [fields and enums documentation](https://opensimulationinterface.github.io/osi-antora-generator/asamosi/latest/specification/contr …
=> Add new enum Type in vehicle classification for stand-up scooters

doc/images/OSI_ReferenceLine1.svg, doc/images/OSI_ReferenceLine2.svg, osi_referenceline.proto
This addresses #645 
Current definition of s,t coordinates has some (well documented) downsides, which we would like to mitigate with this proposed change. With the updated s,t definition, x,y <-> s,t associations are unique inside the lane geometries and there are no gaps in the s coordinate anymore.
This approach is used and tested by [openPASS ](https://gitlab.eclipse.org/eclipse/simopenpass/simopenpass).
Checks will follow (but the links to `howtocontribute.html` seem to be dead... where to get this information?)
=> Adapt ReferenceLine ST definition to avoid transformation ambiguity and discontinuities

osi_trafficsign.proto
Issue: #635
ASAM OSI and ISO 23150 or AUTOSAR ADI have a common history. Unfortunately, the inner structure, the naming and the definitions of the standards are differentiated from each other. This makes the work of developers unnecessary complicated for mostly no technical reasons. All sides should strive to reduce inequality.
osi_trafficsign.proto message TrafficSignValue { enum Unit } need an entry which describes the day of the month.
Furthermore, the type need a entry kHour which describe the hour of the day.
The checks will follow.
ISO23150:2021A.2.67 Sign value unit:
@ThomasNaderBMW @jdsika @schmidtlorenz
=> Add DAY to TrafficSign-Value-Unit and change DAY to WEEKDAY

osi_hostvehicledata.proto
Include velocity, acceleration and orientation rate data related to the vehicle coordinate system in the host_vehicle_data message
Signed-off-by: Maikol Drechsler <maikol.drechsler@carissma.eu>
Due to the deprecation of localization and localization_rmse attributes of host_vehicle_data the velocity, acceleration and yaw_rate of the vehicle cannot be described.
The issue had been discussed per e-mail with @ThomasNaderBMW
Include a new attribute vehicle_kinametics which include the ego velocity, orientation rate and acceleration in the host_vehicle_data. 
Include a new attribute, that enables the exchange of vehicle kinematics data.  
The data lost by the deprecation of the …
=> Update host vehicle data with kinematics data

osi_logicaldetectiondata.proto
This is necessary to represent Ibeo LUX ECU data or similar that contain fused lidar point clouds with echo pulse width instead of intensity.
=> Adding the missing field for echo pulse width to logical detections

osi_logicallane.proto
The street name is helpful when displaying the map (e.g. for navigation purposes). The street name is added to the logical lanes, since the street name will typically come from the underlying map, and most map formats are more similar to logical lanes than to physical lanes.
=> Logical lanes: add street name

osi_sensorview.proto, osi_sensorviewconfiguration.proto
Signed-off-by: RIFJo <jochmann@rt.rif-ev.de>
refers to #620
Adds a "pixel_order" field and enum to allow mirrored versions of the pixel layouts.  This is the result of the discussions with the participants in the sensor modelling workgroup meetings.
This pull request also includes the changes from Thomas Sedlmayer in https://github.com/OpenSimulationInterface/open-simulation-interface/pull/684
=> (feat SensorModelling) add pixel_order field

README.md, doc/_config.adoc, doc/architecture/trace_file_example.adoc, doc/open-simulation-interface_user_guide.adoc
This PR should solve #719.
As discussed in the last CCB meeting, we should change the README to only link to the usage examples in the official documentation.
Required steps:
- Move current example as an example to trace-file section in the docu
- Add links in the README to trace file section and OSMP examples
=> Links in README and example moved to docu

osi_detectedlane.proto, osi_detectedobject.proto, osi_detectedroadmarking.proto, osi_detectedtrafficlight.proto, osi_detectedtrafficsign.proto, osi_featuredata.proto, osi_logicaldetectiondata.proto, osi_sensorview.proto
Resolves #712 
- I removed the incorrect parent frame definition for detected moving object base and base_rmse.
- I added definitions of the respective parent frame for all SensorData objects (moving objects, stationary objects, traffic sign, traffic light, road marking, lane boundary). Some of those SensorData objects have example images where the reference frame of the detected objects is shown to be the vehicle coordinate system (with its origin in the center of the rear axle of the ego vehicle). Though, this only applies if virtual mounting position and orientation are set to (0,0,0) for x, y, z and yaw, pitch, roll. I tried to clarify those images by adding some explanation.
=> Fix sensordata reference frame definitions

doc/setup/installing_prerequisites.adoc, doc/setup/installing_windows_cpp.adoc
Adds additional vcpkg build information from OSMP, drops redundant build steps in prerequisites, moving them to the installing documentation.
=> Move missing vcpkg information to prerequisites

.gitmodules, CMakeLists.txt, osi_lane.proto, osi_object.proto, osi_trafficsign.proto
This  pull request collects all fixes to the flatbuffer build to make it fully functional:
- Fix CMake build breakage due to better separation of source and binary directories in #551
- Replace flatbuffers submodule with find_package dependency
- Temporary work-around for flatc bug with same-named nested enum types
- Add project-scoped alias for flatbuffers-based library
=> Fix flatbuffer builds for upcoming release

osi_featuredata.proto
#307
Added radial_velocity to LidarDetection as FMCW lidars are capable of measuring the relative radial velocity.
=> Added radial_velocity to LidarDetection

osi_featuredata.proto
Added beam_id as an identifier to LidarDetection.
Now, individual detection points can be assigned to a lidar beam. This enables the identification of multiple returns in one beam and also aligns with the output of some real lidar sensors, e.g. Velodynes.
=> Add beam ID to LidarDetection

CMakeLists.txt
=> Make CMAKE_CXX_STANDARD overridable (fix #741)

.github/workflows/protobuf.yml, .gitignore, format/OSITrace.py, format/osi2read.py, format/txt2osi.py, requirements_develop.txt, setup.py, tests/test_comment_type.py, tests/test_doxygen_output.py, tests/test_invalid_comment.py, tests/test_invalid_enum.py, tests/test_invalid_html.py, tests/test_invalid_message.py, tests/test_invalid_punctuation.py, tests/test_invalid_tabs.py, tests/test_newline.py, tests/test_non_ascii.py, tests/test_rules.py, tests/test_units.py
* Add .venv/ and venv/ to .gitignore
* Bump Python minimum to 3.8 as out of support
* Update GitHub Marketplace Actions
* Add workflow to check black formatting
* Add requirements_develop.txt
* Apply black formatting
=> Workflow: Update Python and Actions + Black formatting Python files

osi_object.proto
#747 
Add orientation rate to the bone class. The translatory velocity of the bones can be calculated with the orientation rate of the parent bones.
=> Add orientation rate to PedestrianAttributes::Bone

osi_common.proto
This PR is a continuation of #695 (and #685) with fixed history. It proposes the addition of bounding box sub-sections to BaseMoving and BaseStationary objects, to help sub-divide and classify different parts of the overall object structure.
=> Add new message for sub-bounding boxes

.github/workflows/antora-generator.yml, .github/workflows/protobuf.yml, .github/workflows/release.yml
=> Update github actions for release workflow

.github/workflows/protobuf.yml
As decided in the CCB 2023-12-04 based on the issue fixed in #744, this adds checks to the build infrastructure to check that all proto files are actually referenced in CMakeLists.txt and setup.py.
=> Add check that all proto files are included in build

osi_common.proto, osi_sensordata.proto
[733](https://github.com/OpenSimulationInterface/open-simulation-interface/issues/733)
see Issue
=> feat: Add virtual detection area

osi_object.proto
We should not include todo notes concerning other standards in OSI's documentation. Apparently, such todo notes are prominentely displayed in the documentation menu tree.
=> Remove OSC todo comment from source_reference

doc/architecture/architecture_overview.adoc, doc/architecture/feature_data.adoc, doc/architecture/sensor_data.adoc, doc/open-simulation-interface_user_guide.adoc
As discussed in the last Performance/Packaging WG meeting, I created this pull request to remove any comments from the documentation that suggest that FeatureData could be a top-level message. Since FeatureData does not even contain the simulation timestamp, it can not be used as a top-level message at present anyway. This probably was an oversight from earlier documentation activities.
Resolves #771
=> Fix documentation on FeatureData messages

.github/.pyspelling.yml, .github/spelling_custom_words_en_US.txt
I noticed that adding new hyperlinks to the proto files requires to add any character sequences from the hyperlink as exceptions to the spellchecker (see #790). So I found that it is possible to add a html filter that excludes such character sequences.
[Here](https://github.com/thomassedlmayer/open-simulation-interface/commit/0b376bce907a40fdebc05d480a204625f8db9b61) I added a exemplary `<a>`-tag with a hyperlink that contains strings that should trigger a spellchecker fail. With the new html filter the hyperlink does not trigger the fail anymore but now it fails because it now detects a lot more strings that contain mutated vowels which were not detected before. I guess the html filter converts those special characters so that the spellchecker can also check those words.
@ClemensLinnhoff …
=> Add pyspelling html filter

osi_object.proto
This is a first result of the harmonization effort across ASAM Open standards
In preparation of additional types we already deprecate some obvious candidates for removal, namely our plethora of car types.
=> Deprecate various car types in favor of new alias TYPE_CAR

osi_logicallane.proto
Introduce a message for traffic rule information for logical lanes. The message is intended to be used by traffic participants to easily get information in traffic rules without having to process traffic signs or other additional information.
While this contains an implementation for a speed limit traffic rule the message is designes so that it can be extended with additional traffic rule types in the future.
=> Logical Traffic Rules and Speed Limit

.github/workflows/protobuf.yml
Initial support for publishing of snapshot releases to TestPyPI.
=> Add initial TestPyPI package publishing

osi3trace/osi_trace.py, tests/test_osi_trace.py
﻿As identified by @ClemensLinnhoff there is a precedence error in retrieve_offsets which can lead to errors if the function is called again after a completed read.
This PR fixes this bug and adds a test case to detect such errors.
=> Fix osi trace robustness

osi_sensorviewconfiguration.proto
#770
A slight improvement and additional information for the description of the SensorViewConfiguration's omit_static_information data field.
=> Improve omit_static_information field description

doc/setup/installing_linux_python.adoc, doc/setup/installing_windows_python.adoc
Adjust python install instructions to be more uniform across platforms and to reflect availability of packages on PyPI.
=> Update and harmonize python installation instructions

doc/architecture/formatting_script.adoc, doc/open-simulation-interface_user_guide.adoc
Fixes outdated documentation on osi3trace formatting scripts:
- Fixed folder specification.
- Fixed default value info for `output` arg.
- Removed `format` arg info.
- Changed documentation file name and header from plural to singular because there is only one formatting script left.
=> Fix outdated documentation on formatting scripts

osi_common.proto, osi_detectedobject.proto, osi_route.proto, osi_trafficcommand.proto
#805 
Added rules according to existing notes in the documentation.
=> Add rules according to notes in the documentation

doc/architecture/trace_file_naming.adoc
Added hvd as a supported trace file type for HostVehicleData
We are using OSI to send data within our test vehicle. Within the vehicle, we are just sending HostVehicleData information, because other data is not required. To have data for testing and evaluation, tracing that HostVehicleData should be available in a general fashion.
This change is just an extension in the naming conventions, which will allow saving HostVehicleData as hvd files.
=> Added hvd as a trace file type for HostVehicleData

osi_sensorviewconfiguration.proto
Issue #699
Reformatted to utilize the ray tracing approach
Offers a generic description, independent of tool provider or sensor technology
Format of the Raytracing View.
Content of the Raytracing View
Name of the enum
Reduces dependency on specific tools and technologies
Facilitates standardization and unification
proposal
=> 689 add raytracerview config - RAYTRACER_FORMAT

osi_common.proto, osi_detectedobject.proto, osi_detectedroadmarking.proto, osi_detectedtrafficlight.proto, osi_detectedtrafficsign.proto, osi_object.proto, osi_roadmarking.proto, osi_trafficlight.proto, osi_trafficsign.proto
=> Fix incorrect reference system documentation for detected objects in BaseMoving

osi_lane.proto, osi_logicallane.proto, osi_sensorview.proto
`LogicalLane::PhysicalLaneReference` has a rule `refer_to: Lane` which can not be checked because there is no specification of which field inside PhysicalLaneReference contains the relevant id to be checked.
The `physical_lane_id` field has this rule as well (see [here](https://opensimulationinterface.github.io/osi-antora-generator/asamosi/V3.5.0/gen/structosi3_1_1LogicalLane_1_1PhysicalLaneReference.html#a3fdd0c1928556254713f31168c76ae1c)). There it can be properly checked.
I removed the rule that is both redundant and incorrectly located. I guess the `refers_to` rule can only be used for Identifiers.
Resolves #848
=> Fix multiple rule bugs

osi_common.proto
=> Fix orientation3d formatting bug
